# Generated by Django 2.0.13 on 2020-01-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190804_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bonus_level_id',
            field=models.IntegerField(default=1),
        ),
    ]
