# Generated by Django 2.2 on 2021-03-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210319_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='details_done',
            field=models.BooleanField(default=0),
        ),
    ]
