# Generated by Django 3.2.5 on 2022-01-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_player_details_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='department',
            field=models.CharField(choices=[('Aerospace Engineering', 'Aerospace Engineering'), ('Centre for Environmental Science and Engineering', 'Centre for Environmental Science and Engineering'), ('Chemical Engineering', 'Chemical Engineering'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('Energy Science and Engineering', 'Energy Science and Engineering'), ('Humanities & Social Science', 'Humanities & Social Science'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical Engineering & Materials Science', 'Metallurgical Engineering & Materials Science'), ('Physics', 'Physics'), ('Others', 'Others')], max_length=255),
        ),
    ]
