# Generated by Django 3.2 on 2022-01-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
