"""
Django settings for SARCasm project.
Generated by 'django-admin startproject' using Django 2.2.2.
For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATIC_DIR = os.path.join(BASE_DIR,'static/static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#&&*vy%5w*&7vnrga=9m44a7=4+1%*&3z*envjglrt@_yqm_ih'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.105.177.155', '104.131.4.40','127.0.0.1', 'localhost','sarcasm.sarc-iitb.org', 'www.sarcasm.sarc-iitb.org']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'game',
    'users',
    'ckeditor',
    'social_django',
    'crispy_forms',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # <--
]

ROOT_URLCONF = 'SARCasm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect', # <--

            ],
        },
    },
]

WSGI_APPLICATION = 'SARCasm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
    'toolbar': 'basic',
    'height': 400,
    'width': '100%',
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# MEDIA_ROOT = os.path.join(BASE_DIR, '')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'nginx/static/')
STATICFILES_DIRS = (
    STATIC_DIR,
)

# MEDIA_URL = '/media/'
#MEDIA_ROOT ='./nginx/static/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media')
MEDIA_URL = '/media/'
# STATICFILES_DIRS=(
#     os.path.join(BASE_DIR,static)
# )

CRISPY_TEMPLATE_PACK='bootstrap4'

# LOGIN_REDIRECT_URL='game-home'

EMAIL_BACKEND= 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST= 'localhost'
EMAIL_PORT=1025
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER= 'sarc.web19@gmail.com'
# EMAIL_HOST_PASSWORD='avzhppuivcflbnav'
AUTHENTICATION_BACKENDS = (
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.google.GoogleOAuth',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = "641003495765-da54nk1vbpnkkr7ms9c05c4om5qekkm0.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "Ndo0w4MqjrIpgx_Vd0fI4yHA"
# SOCIAL_AUTH_GOOGLE_OAUTH_SCOPE = []
# SOCIAL_AUTH_FACEBOOK_KEY='766072797538520'
# SOCIAL_AUTH_FACEBOOK_SECRET='bf94e969ed311a60fa81033333f9109b'

LOGIN_URL = 'game-play'
LOGOUT_URL = 'game-home'
LOGIN_REDIRECT_URL = 'register'
