# Generated by Django 2.0.13 on 2020-01-01 18:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190808_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusQuestion',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', ckeditor.fields.RichTextField(blank=True)),
                ('answer', models.CharField(max_length=120)),
                ('expiration_date', models.DateTimeField()),
                ('live_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('audiofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='static/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='level',
            name='is_bonus',
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
