# Generated by Django 2.0.13 on 2020-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20200101_1802'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusQuestion',
        ),
        migrations.AddField(
            model_name='level',
            name='is_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
